[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev:vite"
  port = 3000
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200